### ISSUE TITLE
Add "full_codename" or something to the Release object

### ISSUE THREAD

**Issue by nottrobin** [powersj/ubuntu-release-info#2]
I was hoping to use this library to retrieve the full codename (e.g. "Bionic Beaver"), from the release number ("18.04").

I was able to do achieve this with `python-distro-info` through `UbuntuDistroInfo().get_all("object")`, but I can't actually install python-distro-info in the context I need it, so I was excited to use this instead.

At the moment, `Data().by_release("18.04")` returns simply "bionic", and there's no second option to ask it for a full object or more data as there is with the `python-distro-info` functions. Would it be possible to add an option to get the full `Release` object returned instead of simply the short codename string?

**Comment by nottrobin** [comment]
Oh actually it is an object returned. I didn't realise 'cos it's printed out as a short codename. This works okay, the only feature request I'd add is the ability to get the "full codename" (Bionic Beaver) on the release object. At the moment I have to use regex to extract it from the long "name" property.

**Comment by powersj** [comment]
Uploaded 20.2 to PyPI.

**Comment by powersj** [comment]
Thanks for this!
